name: Domains
favicon: null
layout_spectrum: 0.50704
typography_spectrum: 0.29177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6666a4'
    - '#e00000'
    - '#07223f'
    - '#fad15f'
  brandStrength: 0.6200893418863416
  lightness: 0.2947724489495158
  saturation: 0.05712886503897607
  rhythmicContrast: 0.9531050701625645
purpose: []
